import * as React from "react";
import Layout from "../../layouts/Default";
import { Block } from "baseui/block";
import { useStyletron } from "baseui";
import ProfileSide from "../../components/browse/profile/ProfileSide";
import ContentSide from "../../components/browse/profile/ContentSide";
import restricted from "../api/restricted";
import Head from "next/head";
import { useRouter } from "next/router";
import { trpc } from "../../utils/trpc";
import { style } from "../../styles/StyleObject";

// FOR RESTRICTED AUTH PURPOSE
export const getServerSideProps = restricted(async (ctx) => {
  return { props: {} };
});

export default function Profile() {
  const [css] = useStyletron();
  const router = useRouter();
  const { id } = router.query;

  const { data } = trpc.useQuery(["worker.profile", { id: id as string }], {
    retry: false,
  });
  return (
    <Layout hasHeader={true}>
      <Head>
        <title>{data?.profile?.user?.username} | Housemade</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Block
        display={"flex"}
        flexDirection={["column", "column", "column", "row"]}
        className={css(style.profileDefaultLayout)}
      >
        {/* Profile */}
        <ProfileSide />

        {/* Content */}
        <ContentSide />
      </Block>
    </Layout>
  );
}
