import * as React from "react";
import Layout from "../../layouts/Default";
import { Block } from "baseui/block";
import { useStyletron } from "baseui";
import { useRouter } from "next/router";
import { AspectRatioBox, AspectRatioBoxBody } from "baseui/aspect-ratio-box";
import Image from "next/image";
import {
  DisplaySmall,
  DisplayXSmall,
  ParagraphMedium,
  ParagraphSmall,
} from "baseui/typography";
import { trpc } from "../../utils/trpc";
import Head from "next/head";
import { style } from "../../styles/StyleObject";

export default function Project() {
  const [css] = useStyletron();
  const router = useRouter();
  const { id } = router.query;
  const { data, isLoading } = trpc.useQuery(
    ["project.project", { id: id as string }],
    { retry: false, enabled: Boolean(id) }
  );
  const proj = data && data.project;

  return (
    <Layout hasHeader={true}>
      <Head>
        <title>{data?.project.title} | Housemade</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {proj === undefined || isLoading ? (
        <>is loading...</>
      ) : (
        <>
          <AspectRatioBox aspectRatio={16 / 9}>
            <AspectRatioBoxBody
              display="flex"
              flexDirection="column"
              width="100%"
              className={css(style.imageContainer)}
            >
              <Image
                alt={proj.title}
                src={proj.imageURL || ""}
                objectFit="cover"
                priority
                layout="fill"
                className={css(style.image)}
              />
            </AspectRatioBoxBody>
          </AspectRatioBox>
          <Block
            display="flex"
            flexDirection={["column", "column", "row", "row"]}
            padding={["20px 0", "30px 0", "40px 0", "50px 0"]}
            className={css({
              gap: "5%",
            })}
          >
            <Block
              flex="0 30%"
              display="flex"
              flexDirection="column"
              className={css({
                gap: "10px",
              })}
            >
              <DisplayXSmall
                margin={0}
                display={["block", "block", "none", "none"]}
              >
                {proj.title}
              </DisplayXSmall>
              <DisplaySmall
                margin={0}
                display={["none", "none", "block", "block"]}
              >
                {proj.title}
              </DisplaySmall>
              <ParagraphMedium margin={["0 0 20px 0", "0 0 20px 0", 0, 0]}>
                Client : {proj.client}
              </ParagraphMedium>
            </Block>
            <Block flex={"0 65%"}>
              <ParagraphSmall margin={0}>{proj.description}</ParagraphSmall>
            </Block>
          </Block>
        </>
      )}
    </Layout>
  );
}
