import * as React from "react";
import { useRouter } from "next/router";
import Layout from "../../layouts/Default";
import { FlexGrid, FlexGridItem } from "baseui/flex-grid";
import { StatefulButtonGroup, MODE, SIZE, SHAPE } from "baseui/button-group";
import { Button } from "baseui/button";
import { Block } from "baseui/block";
import { trpc } from "../../utils/trpc";
import WorkerBtn from "../../components/common/WorkerBtn";
import restricted from "../api/restricted";
import Head from "next/head";
import { HeadingTitle } from "../../components/shared/HeadingTitle";

// FOR RESTRICTED AUTH PURPOSE
export const getServerSideProps = restricted(async (ctx) => {
  return { props: {} };
});

export default function Worker() {
  const router = useRouter();
  const { id, skillId } = router.query;

  const cate = trpc.useQuery(["category.category", { id: id as string }], {
    retry: false,
  });
  const subcategoryQuery = trpc.useQuery(
    ["subcategory.subcategories", { id: id as string }],
    { retry: false }
  );
  const { data } = trpc.useQuery(
    ["worker.workers", { id: (skillId as string) || (id as string) }],
    { retry: false }
  );

  console.log(data?.workers);

  return (
    <Layout hasHeader={true}>
      <Head>
        <title>{cate.data?.category?.title} | Housemade</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeadingTitle title={cate.data?.category?.title || ""} />
      <Block marginBottom={"20px"}>
        <StatefulButtonGroup
          size={SIZE.compact}
          shape={SHAPE.pill}
          mode={MODE.radio}
          initialState={{ selected: 0 }}
        >
          <Button
            onClick={() => {
              router.push(`/browse/Worker?id=${id}`);
            }}
          >
            All
          </Button>
          {subcategoryQuery.data?.subcategories.map((skill) => (
            <Button
              key={skill.id.toString()}
              onClick={() => {
                router.push(`/browse/Worker?id=${id}&skillId=${skill.id}`);
              }}
            >
              {skill.title}
            </Button>
          ))}
        </StatefulButtonGroup>
      </Block>
      <FlexGrid
        flexGridColumnCount={[1, 1, 2, 3]}
        flexGridColumnGap="scale500"
        flexGridRowGap="scale500"
      >
        {data?.workers.map((worker) => {
          return (
            <FlexGridItem key={worker.id}>
              <WorkerBtn
                id={worker.id}
                pfp={worker.imageURL}
                username={worker.user.username}
                verify={worker.verify}
                skill={worker.subcategory.title}
                rating={worker.rating}
                reviewer={worker.reviewer}
              />
            </FlexGridItem>
          );
        })}
      </FlexGrid>
    </Layout>
  );
}
