import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useCallback, useState } from "react";
import { signIn, SignInResponse, useSession } from "next-auth/react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";

import { loginSchema, ILogin } from "../../utils/auth-validation";
import { useRouter } from "next/router";

const LogIn: NextPage = () => {
  const router = useRouter();
  const { register, handleSubmit } = useForm<ILogin>({
    resolver: zodResolver(loginSchema),
  });
  const [error, setError] = useState<SignInResponse["error"]>();

  const { status } = useSession();

  if (status === "authenticated") {
    router.push("/browse/Browse");
  }

  const onSubmit = useCallback(async (data: ILogin) => {
    await signIn("credentials", {
      ...data,
      callbackUrl: "/dashboard",
      redirect: false,
    }).then((res) => {
      console.log(res, "logooin")
      if (res?.ok) {
        router.push("/dashboard");
      } else {
        setError('Invalid credentials!');
      }
    });
  }, []);

  return (
    <div>
      <Head>
        <title>Next App - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <form
          className="flex items-center justify-center h-screen w-full"
          onSubmit={handleSubmit(onSubmit)}
        >
          <div className="card w-96 bg-base-100 shadow-xl">
            <div className="card-body bg-neutral-focus">
              <h2 className="card-title">Welcome back!</h2>
              {error && <span className="alert alert-error">{error}</span>}
              <input
                type="email"
                placeholder="Type your email..."
                className="input input-bordered w-full max-w-xs mt-2"
                {...register("email")}
              />
              <input
                type="password"
                placeholder="Type your password..."
                className="input input-bordered w-full max-w-xs my-2"
                {...register("password")}
              />
              <input type="submit" hidden />
              <div className="card-actions items-center justify-between">
                <Link href="/authentication/Signup" className="link">
                  Go to sign up
                </Link>
                <button className="btn btn-secondary" type="submit">
                  Login
                </button>
              </div>
            </div>
          </div>
        </form>
      </main>
    </div>
  );
};

export default LogIn;
