import * as React from "react";
import { FlexGrid, FlexGridItem } from "baseui/flex-grid";
import Default from "../../layouts/Default";
import { HeadingTitle } from "../../components/shared/HeadingTitle";
import { useStyletron } from "baseui";
import { Accordion, Panel } from "baseui/accordion";
import { RequestBooking } from "../../components/schedule/RequestBooking";
import { Requesting } from "../../components/schedule/Requesting";
import { trpc } from "../../utils/trpc";
import { useSession } from "next-auth/react";
import restricted from "../api/restricted";
import Head from "next/head";
import { UpcomingDefaultAsWorker } from "../../components/schedule/UpcomingDefaultAsWorker";
import { UpcomingEndingAsWorker } from "../../components/schedule/UpcomingEndingAsWorker";
import { UpcomingEndingRecieverAsWorker } from "../../components/schedule/UpcomingEndingRecieverAsWorker";
import { CompletedAsClient } from "../../components/schedule/CompletedAsClient";
import { CompletedAsWorker } from "../../components/schedule/CompletedAsWorker";
import { UpcomingDefaultAsClient } from "../../components/schedule/UpcomingDefaultAsClient";
import { UpcomingEndingAsClient } from "../../components/schedule/UpcomingEndingAsClient";
import { UpcomingEndingRecieverAsClient } from "../../components/schedule/UpcomingEndingRecieverAsClient";

// FOR RESTRICTED AUTH PURPOSE
export const getServerSideProps = restricted(async (ctx) => {
  return { props: {} };
});

// Wrapper
export const ScheduleWrapper = ({
  children,
}: {
  children: React.ReactNode;
}) => {
  const [css, theme] = useStyletron();

  return (
    <Accordion
      onChange={({ expanded }) => console.log(expanded)}
      accordion
      overrides={{
        Header: {
          style: () => ({
            backgroundColor: theme.colors.backgroundSecondary,
          }),
        },
        Content: {
          style: () => ({
            paddingTop: "0px",
            paddingBottom: "0px",
            paddingLeft: "0px",
            paddingRight: "0px",
          }),
        },
      }}
    >
      {children}
    </Accordion>
  );
};

export default function Schedule() {
  const { data: session } = useSession();
  const { data } = trpc.useQuery(
    ["schedule.appointments", { userId: session?.id as string }],
    { retry: false }
  );
  return (
    <Default hasHeader={true}>
      <Head>
        <title>Schedule | Housemade</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeadingTitle title="Schedule" />
      <FlexGrid
        flexGridColumnCount={[1, 1, 2, 3]}
        flexGridColumnGap="scale500"
        flexGridRowGap="scale500"
        justifyContent="center"
      >
        <FlexGridItem>
          <ScheduleWrapper>
            <Panel title="Requesting...">
              {data?.appointments.map((item) => {
                if (item.status === "request") {
                  if (item.clientId === session?.id) {
                    return <Requesting scheduleData={item} key={item.id} />;
                  }
                  return <RequestBooking scheduleData={item} key={item.id} />;
                }
              })}
            </Panel>
          </ScheduleWrapper>
        </FlexGridItem>
        <FlexGridItem>
          <ScheduleWrapper>
            <Panel title="Upcoming Appointment">
              {data?.appointments.map((item) => {
                if (item.status === "upcoming") {
                  if (item.upcoming_status === "default") {
                    if (item.clientId === session?.id) {
                      return (
                        <UpcomingDefaultAsClient
                          scheduleData={item}
                          key={item.id}
                        />
                      );
                    }
                    return (
                      <UpcomingDefaultAsWorker
                        scheduleData={item}
                        key={item.id}
                      />
                    );
                  } else if (
                    item.upcoming_status === "ending" &&
                    session?.id != item.senderId
                  ) {
                    if (item.clientId === session?.id) {
                      return (
                        <UpcomingEndingAsClient
                          scheduleData={item}
                          key={item.id}
                        />
                      );
                    }
                    return (
                      <UpcomingEndingAsWorker
                        scheduleData={item}
                        key={item.id}
                      />
                    );
                  } else if (
                    item.upcoming_status === "ending" &&
                    item.senderId === session?.id
                  ) {
                    if (item.clientId === session?.id) {
                      return (
                        <UpcomingEndingRecieverAsClient
                          scheduleData={item}
                          key={item.id}
                        />
                      );
                    }
                    return (
                      <UpcomingEndingRecieverAsWorker
                        scheduleData={item}
                        key={item.id}
                      />
                    );
                  }
                }
              })}
            </Panel>
          </ScheduleWrapper>
        </FlexGridItem>
        <FlexGridItem>
          <ScheduleWrapper>
            <Panel title="Completed Appointment">
              {data?.appointments.map((item) => {
                if (item.status === "completed") {
                  if (item.clientId === session?.id) {
                    return (
                      <CompletedAsClient scheduleData={item} key={item.id} />
                    );
                  }
                  return (
                    <CompletedAsWorker scheduleData={item} key={item.id} />
                  );
                }
              })}
            </Panel>
          </ScheduleWrapper>
        </FlexGridItem>
      </FlexGrid>
    </Default>
  );
}
