import { useStyletron } from "baseui";
import * as React from "react";
import { Button, SIZE, SHAPE } from "baseui/button";
import { MODE, StatefulButtonGroup } from "baseui/button-group";
import { FormControl } from "baseui/form-control";
import Head from "next/head";
import { style } from "../../styles/StyleObject";

export default function AppearenceSetting() {
  const [css] = useStyletron();
  return (
    <div className={css(style.settingDefaultLayout)}>
      <Head>
        <title>Appearence | Housemade</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <FormControl label="Language">
        <StatefulButtonGroup
          mode={MODE.radio}
          size={SIZE.compact}
          shape={SHAPE.pill}
          initialState={{ selected: 0 }}
        >
          <Button onClick={() => {}}>English</Button>
          <Button onClick={() => {}}>ខ្មែរ</Button>
          <Button onClick={() => {}}>ไทย</Button>
        </StatefulButtonGroup>
      </FormControl>
      <FormControl label="Theme">
        <StatefulButtonGroup
          mode={MODE.radio}
          size={SIZE.compact}
          shape={SHAPE.pill}
          initialState={{ selected: 0 }}
        >
          <Button onClick={() => {}}>Light Mode</Button>
          <Button onClick={() => {}}>Dark Mode</Button>
        </StatefulButtonGroup>
      </FormControl>
      s
    </div>
  );
}
